# Regenerated by scripts/update-packaging.sh from the release archives. Edit
# that script, not this file.
class Alphawinnow < Formula
  desc "Typed, deterministic formulaic alpha-mining and factor-evaluation engine"
  homepage "https://github.com/eslazarev/alphawinnow"
  version "0.1.2"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/eslazarev/alphawinnow/releases/download/v0.1.2/alphawinnow-0.1.2-aarch64-apple-darwin.tar.gz"
      sha256 "3d781f945c05e9c23bc31b23e8758d7d076755c87f84eb0026ed1c6f60ea186b"
    end
    on_intel do
      url "https://github.com/eslazarev/alphawinnow/releases/download/v0.1.2/alphawinnow-0.1.2-x86_64-apple-darwin.tar.gz"
      sha256 "eb61b569980f6017ab5d338b62ecbb3e6eac5f43070319edfb4facf014ad9ed2"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/eslazarev/alphawinnow/releases/download/v0.1.2/alphawinnow-0.1.2-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "c316bddeaa0d0d63368f62fc1fd9fa847b0333267d90d24f4a5333a2894d65a6"
    end
    on_intel do
      url "https://github.com/eslazarev/alphawinnow/releases/download/v0.1.2/alphawinnow-0.1.2-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "eb813d1522b131f16a0c9895c41efec935cda90c51099d8b2acd41e31fc7f88f"
    end
  end

  def install
    bin.install "alphawinnow"
    doc.install "README.md", "LICENSE"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/alphawinnow --version")
    # `doctor` is the offline self-check; it must not touch the network.
    assert_match "\"ready\":true", shell_output("#{bin}/alphawinnow doctor --json")
  end
end
