# Regenerated by scripts/update-packaging.sh from the release archives. Edit
# that script, not this file.
class Alphawinnow < Formula
  desc "Typed, deterministic formulaic alpha-mining and factor-evaluation engine"
  homepage "https://github.com/eslazarev/alphawinnow"
  version "0.1.1"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/eslazarev/alphawinnow/releases/download/v0.1.1/alphawinnow-0.1.1-aarch64-apple-darwin.tar.gz"
      sha256 "19f4749d674034f6ed778d6cc95d110948f2e98d630a4f1190739f2e07968b0d"
    end
    on_intel do
      url "https://github.com/eslazarev/alphawinnow/releases/download/v0.1.1/alphawinnow-0.1.1-x86_64-apple-darwin.tar.gz"
      sha256 "e7859cf002e0a4657229a10fec05029d0dd48dd969d7ac20e5d40e18860ebc33"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/eslazarev/alphawinnow/releases/download/v0.1.1/alphawinnow-0.1.1-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "21c2867590a202eda6367a13132a76f8cf31154b4edd44821a3761623a8bbfe0"
    end
    on_intel do
      url "https://github.com/eslazarev/alphawinnow/releases/download/v0.1.1/alphawinnow-0.1.1-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "292ce9f0474cd5db4d6e47a5e0c8d28c0cc68c092a27dfde698cb70980c8a34e"
    end
  end

  def install
    bin.install "alphawinnow"
    doc.install "README.md", "LICENSE"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/alphawinnow --version")
    # `doctor` is the offline self-check; it must not touch the network.
    assert_match "\"ready\":true", shell_output("#{bin}/alphawinnow doctor --json")
  end
end
