# Regenerated by scripts/update-packaging.sh from the release archives. Edit
# that script, not this file.
class Alphawinnow < Formula
  desc "Typed, deterministic formulaic alpha-mining and factor-evaluation engine"
  homepage "https://github.com/eslazarev/alphawinnow"
  version "0.2.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/eslazarev/alphawinnow/releases/download/v0.2.0/alphawinnow-0.2.0-aarch64-apple-darwin.tar.gz"
      sha256 "d6219060210d9ae131113cc4f82d0a5533fe1a68a32b28c72936a3bd8d9f13e5"
    end
    on_intel do
      url "https://github.com/eslazarev/alphawinnow/releases/download/v0.2.0/alphawinnow-0.2.0-x86_64-apple-darwin.tar.gz"
      sha256 "e9235688b0996a901a8c3e30bf91a25a9fa7b2a7ee840dc2cdb8ff4fc1d373d4"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/eslazarev/alphawinnow/releases/download/v0.2.0/alphawinnow-0.2.0-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "a37eaed048c5d00b8b5d81c8e2b4ed39d7d1fef697d2e2eca2e134d001404618"
    end
    on_intel do
      url "https://github.com/eslazarev/alphawinnow/releases/download/v0.2.0/alphawinnow-0.2.0-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "ba29d1f1a05c8141e2dc8964dbc280b0ccbc0116f3f1e1653bf8eda26e316f6f"
    end
  end

  def install
    bin.install "alphawinnow"
    doc.install "README.md", "LICENSE"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/alphawinnow --version")
    # `doctor` is the offline self-check; it must not touch the network.
    assert_match "\"ready\":true", shell_output("#{bin}/alphawinnow doctor --json")
  end
end
