#!/usr/bin/env bash
# Regenerate the package-manager manifests for a released version.
#
#   scripts/update-packaging.sh <version> <checksum-directory>
#
# The checksum directory holds the `*.sha256` files produced alongside the
# release archives, exactly as the `binaries` job uploads them. Both manifests
# are written in full rather than patched, so the committed file is always a
# function of the release rather than of whatever happened to be there before.
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
VERSION="${1:?usage: update-packaging.sh <version> <checksum-directory>}"
SUMS_DIR="${2:?usage: update-packaging.sh <version> <checksum-directory>}"
REPO="https://github.com/eslazarev/alphawinnow"

# Read the checksum for one target out of `<archive>.sha256`, which holds the
# `sha256sum` line format: "<digest>  <file name>".
digest_for() {
  local target="$1" ext="$2"
  local file="${SUMS_DIR}/alphawinnow-${VERSION}-${target}.${ext}.sha256"
  if [[ ! -f "${file}" ]]; then
    echo "Error: missing checksum file ${file}" >&2
    exit 1
  fi
  local digest
  digest="$(awk '{print $1; exit}' "${file}")"
  if [[ ! "${digest}" =~ ^[0-9a-f]{64}$ ]]; then
    echo "Error: ${file} does not contain a SHA-256 digest" >&2
    exit 1
  fi
  printf '%s' "${digest}"
}

macos_arm="$(digest_for aarch64-apple-darwin tar.gz)"
macos_intel="$(digest_for x86_64-apple-darwin tar.gz)"
linux_arm="$(digest_for aarch64-unknown-linux-gnu tar.gz)"
linux_intel="$(digest_for x86_64-unknown-linux-gnu tar.gz)"
windows="$(digest_for x86_64-pc-windows-msvc zip)"

cat > "${ROOT_DIR}/Formula/alphawinnow.rb" <<FORMULA
# Regenerated by scripts/update-packaging.sh from the release archives. Edit
# that script, not this file.
class Alphawinnow < Formula
  desc "Typed, deterministic formulaic alpha-mining and factor-evaluation engine"
  homepage "${REPO}"
  version "${VERSION}"
  license "MIT"

  on_macos do
    on_arm do
      url "${REPO}/releases/download/v${VERSION}/alphawinnow-${VERSION}-aarch64-apple-darwin.tar.gz"
      sha256 "${macos_arm}"
    end
    on_intel do
      url "${REPO}/releases/download/v${VERSION}/alphawinnow-${VERSION}-x86_64-apple-darwin.tar.gz"
      sha256 "${macos_intel}"
    end
  end

  on_linux do
    on_arm do
      url "${REPO}/releases/download/v${VERSION}/alphawinnow-${VERSION}-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "${linux_arm}"
    end
    on_intel do
      url "${REPO}/releases/download/v${VERSION}/alphawinnow-${VERSION}-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "${linux_intel}"
    end
  end

  def install
    bin.install "alphawinnow"
    doc.install "README.md", "LICENSE"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/alphawinnow --version")
    # \`doctor\` is the offline self-check; it must not touch the network.
    assert_match "\\"ready\\":true", shell_output("#{bin}/alphawinnow doctor --json")
  end
end
FORMULA

cat > "${ROOT_DIR}/packaging/scoop/alphawinnow.json" <<SCOOP
{
    "version": "${VERSION}",
    "description": "Typed, deterministic formulaic alpha-mining and factor-evaluation engine",
    "homepage": "${REPO}",
    "license": "MIT",
    "architecture": {
        "64bit": {
            "url": "${REPO}/releases/download/v${VERSION}/alphawinnow-${VERSION}-x86_64-pc-windows-msvc.zip",
            "hash": "${windows}",
            "extract_dir": "alphawinnow-${VERSION}-x86_64-pc-windows-msvc"
        }
    },
    "bin": "alphawinnow.exe",
    "checkver": {
        "github": "${REPO}"
    },
    "autoupdate": {
        "architecture": {
            "64bit": {
                "url": "${REPO}/releases/download/v\$version/alphawinnow-\$version-x86_64-pc-windows-msvc.zip",
                "extract_dir": "alphawinnow-\$version-x86_64-pc-windows-msvc"
            }
        },
        "hash": {
            "url": "\$url.sha256"
        }
    }
}
SCOOP

echo "Regenerated Formula/alphawinnow.rb and packaging/scoop/alphawinnow.json for v${VERSION}" >&2
